# Generated by Django 3.1.5 on 2021-01-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
