# Generated by Django 3.1.5 on 2021-01-29 13:57

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20210129_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=Main.models.Get_UserName, verbose_name='Фото пользователя'),
        ),
    ]
